version: "3.8"

services:
  db:
    container_name: the_keg_postgres_17_2
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TrackMyBus
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-keg
    environment:
      PORT: 9000
      JDBC_URL: jdbc:postgresql://localhost:5432
      DB_NAME: TrackMyBus
      DB_USER: postgres
      DB_PASSWORD: postgres
      MAX_DB_POOL_SIZE: 50
      DB_AUTO_COMMIT: true
    depends_on:
      - db
    ports:
      - "9000:9000"

volumes:
  postgres_data:
