package com.trackmybus.theKeg.features.v1.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data Transfer Object (DTO) representing trip data.
 *
 * The `TripsDto` class is used to transfer data about trips, with a trip being a single instance of a route.
 * This data is typically sourced from the `trips.txt` file.
 *
 * @property routeId The unique identifier for the route, which serves as a lookup reference to [RouteDto].
 * @property serviceId The unique identifier for the service.
 * @property tripId The unique identifier for the trip, which is a numeric autogenerated id that changes when new schedules are uploaded.
 * @property tripHeadsign The headsign for the trip.
 * @property tripShortName The short name of the trip.
 * @property directionId The direction identifier for the trip.
 * @property blockId The block identifier for the trip.
 * @property shapeId The unique identifier for the shape, which serves as a lookup reference to [ShapeDto].
 */
@Serializable
data class TripDto(
    @SerialName("route_id") val routeId: String? = null,
    @SerialName("service_id") val serviceId: String? = null,
    @SerialName("trip_id") val tripId: String? = null,
    @SerialName("trip_headsign") val tripHeadsign: String? = null,
    @SerialName("trip_short_name") val tripShortName: String? = null,
    @SerialName("direction_id") val directionId: Int? = null,
    @SerialName("block_id") val blockId: String? = null,
    @SerialName("shape_id") val shapeId: String? = null,
)
