name: 'CI'
on:
  pull_request:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # Checkout the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew

      - name: Run Kotlin tests
        run: ./gradlew test                # Run Kotlin tests

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: kotlin-test-results
          path: build/test-results/tests/

  report:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4         # Checkout the repository

      - uses: actions/download-artifact@v4
        with:
          name: kotlin-test-results

      - uses: dorny/test-reporter@v1
        with:
          artifact: kotlin-test-results
          name: JUNIT Tests
          path: '*.xml'
          reporter: java-junit